repo: istio/istio
branches:
  - master

jobs:
  - name: istio-unit-tests
    command: [prow/istio-unit-tests.sh]
  - name: istio-lint
    resources: lint
    command: [prow/istio-lint.sh]
  - name: istio-racetest
    command: [prow/racetest.sh]
  - name: istio-shellcheck
    command: [prow/shellcheck.sh]
  - name: istio-codecov
    command: [prow/codecov.sh]

  - name: integ-framework-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.framework.local.presubmit]
  - name: integ-istioctl-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.istioctl.local.presubmit]
    modifiers: [optional]
  - name: integ-galley-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.galley.local.presubmit]
  - name: integ-mixer-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.mixer.local.presubmit]
    modifiers: [optional]
  - name: integ-pilot-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.pilot.local.presubmit]
  - name: integ-security-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.security.local.presubmit]
  - name: integ-telemetry-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.telemetry.local.presubmit]

  - name: integ-framework-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.framework.kube.presubmit]
    requirements: [kind]
  - name: integ-istioctl-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.istioctl.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
  - name: integ-galley-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.galley.kube.presubmit]
    requirements: [kind]
  - name: integ-mixer-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.mixer.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
  - name: integ-pilot-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.pilot.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
  - name: integ-security-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.security.kube.presubmit]
    requirements: [kind]
  - name: integ-telemetry-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.telemetry.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]

  - name: test-e2e-mixer-no_auth
    command: [prow/test-e2e-mixer-no_auth.sh]
    requirements: [boskos]
    modifiers: [optional, hidden, skipped]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "3000m"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "3000m"