# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
  - name: istio-istio
  - name: istio-bots
  - name: istio-client-go
  - name: istio-cni
  - name: istio-common-files
  - name: istio-community
  - name: istio-gogo-genproto
  - name: istio-installer
  - name: istio-istio.io
  - name: istio-pkg
  - name: istio-tests
  - name: istio-istio-postsubmit
  - name: istio-bots-postsubmit
  - name: istio-client-go-postsubmit
  - name: istio-cni-postsubmit
  - name: istio-common-files-postsubmit
  - name: istio-community-postsubmit
  - name: istio-gogo-genproto-postsubmit
  - name: istio-installer-postsubmit
  - name: istio-istio.io-postsubmit
  - name: istio-pkg-postsubmit
  - name: istio-tests-postsubmit

  - name: istio-api
  - name: istio-api-release-1.3
  - name: istio-proxy-presubmits
  - name: istio-proxy-postsubmits
  - name: istio-proxy-presubmits-release-1.3
  - name: istio-proxy-postsubmits-release-1.3
  - name: istio-release
  - name: istio-release-release-1.3
  - name: istio-infrastructure
  - name: istio-tools
  - name: istio-gke # used by sig-gcp config from k8s/test-infra

# Group all dashboards
dashboard_groups:
- name: istio
  dashboard_names:
  - istio-istio
  - istio-bots
  - istio-client-go
  - istio-cni
  - istio-common-files
  - istio-community
  - istio-gogo-genproto
  - istio-installer
  - istio-istio.io
  - istio-pkg
  - istio-tests
  - istio-istio-postsubmit
  - istio-bots-postsubmit
  - istio-client-go-postsubmit
  - istio-cni-postsubmit
  - istio-common-files-postsubmit
  - istio-community-postsubmit
  - istio-gogo-genproto-postsubmit
  - istio-installer-postsubmit
  - istio-istio.io-postsubmit
  - istio-pkg-postsubmit
  - istio-tests-postsubmit

  - istio-api
  - istio-api-release-1.3
  - istio-proxy-presubmits
  - istio-proxy-postsubmits
  - istio-proxy-presubmits-release-1.3
  - istio-proxy-postsubmits-release-1.3
  - istio-release
  - istio-release-release-1.3
  - istio-infrastructure
  - istio-tools
  - istio-gke # used by sig-gcp config from k8s/test-infra
