# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
  - name: istio-presubmits-master
  - name: istio-postsubmits-master
  - name: istio-presubmits-release-1.2
  - name: istio-postsubmits-release-1.2
  - name: istio-release
  - name: istio-infrastructure