defaults:
  branches: [release-1.4]
  repo-whitelist: [operator]


transforms:
# istio/operator release-1.4 test jobs(s) - presubmit(s) and postsubmit(s)
- labels:
    preset-enable-ssh: "true"
  job-type: [presubmit, postsubmit]
  job-blacklist: [release_operator_release-1.4_postsubmit]
