org: istio
repo: bots
image: gcr.io/istio-testing/build-tools:master-6ca22a4265c8306755fc53a5be49ceaeeae92003

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: deploy-policybot
    service_account_name: prowjob-advanced-sa
    regex: '^policybot/'
    types: [postsubmit]
    command:
    - entrypoint
    - make
    - -C
    - policybot
    - deploy
    requirements: [docker]
