org: istio
repo: bots
image: gcr.io/istio-testing/build-tools:master-8eb42e9551b9a67c330aeef783f2498647d91289

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: deploy-policybot
    cluster: test-infra-trusted
    excluded_requirements: [cache]
    node_selector:
      prod: prow
    service_account_name: prowjob-bots-deployer
    regex: '^policybot/'
    types: [postsubmit]
    command:
    - entrypoint
    - make
    - -C
    - policybot
    - deploy
    requirements: [docker]
