org: istio
repo: community
image: gcr.io/istio-testing/build-tools:master-2019-12-03T17-07-58

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    type: postsubmit
    command: [make, sync]
    requirements: [github]
