repo: istio/istio
branches:
  - master

jobs:
  - name: istio-unit-tests
    command: [prow/istio-unit-tests.sh]
  - name: istio-lint
    resources: lint
    command: [prow/istio-lint.sh]
  - name: istio-racetest
    command: [prow/racetest.sh]
  - name: istio-shellcheck
    command: [prow/shellcheck.sh]
  - name: istio-codecov
    command: [prow/codecov.sh]

    # TODO this probably doesn't need boskos
  - name: release-test
    command: [prow/release-test.sh]
    requirements: [boskos]

  - name: integ-framework-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.framework.local.presubmit]
  - name: integ-istioctl-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.istioctl.local.presubmit]
    modifiers: [optional]
  - name: integ-galley-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.galley.local.presubmit]
  - name: integ-mixer-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.mixer.local.presubmit]
    modifiers: [optional]
  - name: integ-pilot-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.pilot.local.presubmit]
  - name: integ-security-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.security.local.presubmit]
  - name: integ-telemetry-local-presubmit-tests
    command: [prow/integ-suite-local.sh, test.integration.telemetry.local.presubmit]
    modifiers: [optional]

  - name: integ-framework-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.framework.kube.presubmit]
    requirements: [kind]
  - name: integ-istioctl-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.istioctl.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
  - name: integ-galley-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.galley.kube.presubmit]
    requirements: [kind]
  - name: integ-mixer-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.mixer.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
  - name: integ-pilot-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.pilot.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
  - name: integ-security-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.security.kube.presubmit]
    requirements: [kind]
  - name: integ-telemetry-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.telemetry.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
  - name: integ-new-install-k8s-presubmit-tests
    command: [prow/integ-suite-kind.sh, test.integration.new.installer]
    requirements: [kind]
    modifiers: [optional]

    # TODO: remove this test, it is a duplicate
  - name: test-e2e-mixer-no_auth
    command: [prow/test-e2e-mixer-no_auth.sh]
    requirements: [boskos]
    modifiers: [optional, hidden, skipped]
  - name: e2e-mixer-no_auth
    command: [prow/e2e-mixer-no_auth.sh]
    requirements: [boskos]

  - name: istio-pilot-e2e-envoyv2-v1alpha3
    command: [prow/istio-pilot-e2e-envoyv2-v1alpha3.sh]
    requirements: [boskos]

  - name: istio_auth_sds_e2e
    command: [prow/e2e_pilotv2_auth_sds.sh]
    requirements: [boskos]

  - name: e2e-dashboard
    command: [prow/e2e-dashboard.sh]
    requirements: [boskos]

  - name: e2e-bookInfoTests-envoyv2-v1alpha3
    command: [prow/e2e-bookInfoTests-envoyv2-v1alpha3.sh]
    requirements: [boskos]
  - name: e2e-bookInfoTests-trustdomain
    command: [prow/e2e-bookInfoTests-trustdomain.sh]
    requirements: [boskos]
    modifiers: [optional]

  - name: e2e-simpleTests
    command: [prow/e2e-simpleTests.sh]
    requirements: [boskos]
  - name: e2e-simpleTests-distroless
    command: [prow/e2e-simpleTests-distroless.sh]
    requirements: [boskos]
    modifiers: [optional, skipped]
  - name: e2e-simpleTestsMinProfile
    command: [prow/e2e-simpleTests-minProfile.sh]
    requirements: [boskos]
    modifiers: [optional, skipped]
  - name: e2e-simpleTests-cni
    command: [prow/e2e-simpleTests-cni.sh]
    requirements: [boskos]
    modifiers: [optional, skipped]

  - name: istio-pilot-multicluster-e2e
    command: [prow/istio-pilot-multicluster-e2e.sh]
    requirements: [boskos]
    modifiers: [optional]

  - name: istio_e2e_cloudfoundry
    command: [make, e2e_cloudfoundry]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "3000m"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "3000m"