org: istio
repo: operator
image: gcr.io/istio-testing/build-tools:2019-10-11T13-37-52
branches:
  - release-1.4

jobs:
  - name: lint
    command: [make, lint]

  - name: mesh
    command: [make, mesh]

  - name: test
    command: [make, test]

  - name: mandiff
    command: [make, mandiff]

  - name: manifest-apply
    command: [entrypoint, prow/e2e_install.sh]
    requirements: [kind]
    modifiers: [optional, hidden]

  - name: gencheck
    command: [make, gen-check]
    modifiers: [optional]

  - name: release
    type: postsubmit
    command: [entrypoint, make, docker.all]
    requirements: [gcp]
