org: istio
repo: pkg
image: gcr.io/istio-testing/build-tools:2019-10-11T13-37-52
branches:
  - release-1.4

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]
