org: istio
repo: test-infra
image: gcr.io/istio-testing/build-tools:2019-10-25T15-41-11

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: check-config
    command: [make, check-config]

  - name: gencheck
    command: [make, gen-check]
