org: istio
repo: tools
support_release_branching: true
image: gcr.io/istio-testing/build-tools:2019-10-24T14-05-17

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: containers
    type: postsubmit
    command: [entrypoint, make, containers]
    resources: build
    regex: 'docker/.+|cmd/.+'
    requirements: [gcp]
    image: gcr.io/istio-testing/istio-builder:v20190807-7d818206

  - name: containers-test
    type: presubmit
    command: [entrypoint, make, containers-test]
    resources: build
    regex: 'docker/.+|cmd/.+'
    requirements: [gcp]
    image: gcr.io/istio-testing/istio-builder:v20190807-7d818206

resources:
  build:
    requests:
      memory: "4Gi"
      cpu: "8000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
